name: build

on:
  push:
    branches:
      - master

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: clang-format
        run: |
          git submodule update --init --recursive
          docker run --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -e ./src/gtitles.c -e ./src/SDL_FontCache.c -e ./include/SDL_FontCache.h -r ./src ./include
  build-binary:
    name: Build binary
    runs-on: ubuntu-20.04
    needs: clang-format
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker caching
        uses: ScribeMD/docker-cache@0.5.0
        id: cache
        continue-on-error: true
        with:
          key: nusspli-docker-cache-${{ hashFiles('Dockerfile') }}
      - name: Build docker image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker build . -t builder
      - name: Build artifacts
        run: |
          echo ${{ secrets.ENC_KEY }} > encryptKeyWith
          docker run --rm -v ${PWD}:/project builder python3 build.py
          cat version.txt >> $GITHUB_OUTPUT
        id: version
      - name: Upload Aroma version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Aroma
          path: out/Aroma/*
          if-no-files-found: warn
      - name: Upload Aroma debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Aroma-DEBUG
          path: out/Aroma-DEBUG/*
          if-no-files-found: error
      - name: Upload Lite version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Lite
          path: out/Lite/*
          if-no-files-found: warn
      - name: Upload Lite debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Lite-DEBUG
          path: out/Lite-DEBUG/*
          if-no-files-found: error
      - name: Upload Channel version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Channel
          path: out/Channel/*
          if-no-files-found: warn
      - name: Upload Channel debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v4
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Channel-DEBUG
          path: out/Channel-DEBUG/*
          if-no-files-found: error
      - name: Get previous tag
        run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: ${{ env.previous_tag && startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter: 'v\d+\.\d+(-ALPHA|-BETA)?'
      - name: Publish release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          artifactContentType: application/zip
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: |
            zips/NUSspli-${{ steps.version.outputs.version }}-Aroma.zip
            zips/NUSspli-${{ steps.version.outputs.version }}-Aroma-DEBUG.zip
            zips/NUSspli-${{ steps.version.outputs.version }}-Channel.zip
            zips/NUSspli-${{ steps.version.outputs.version }}-Channel-DEBUG.zip
            zips/NUSspli-${{ steps.version.outputs.version }}-Lite.zip
            zips/NUSspli-${{ steps.version.outputs.version }}-Lite-DEBUG.zip
