name: build

on:
  push:
    branch:
      - master

jobs:
#  clang-format:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: clang-format
#        run: |
#          git submodule update --init --recursive
#          docker run --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -e gtitles.c -e gtitles.h -e SDL_FontCache.c -e SDL_FontCache.h -r ./src ./include
  build-binary:
    name: Build binary
    runs-on: ubuntu-20.04
#    needs: clang-format
    steps:
      - name: update container
        run: |
          mkdir -p /usr/share/man/man1 /usr/share/man/man2
          /bin/bash -c "$(curl -sL https://raw.githubusercontent.com/V10lator/NUSspli/master/apt-fast/install.sh)"
          apt-fast -y --no-install-recommends upgrade
          apt-fast -y install --no-install-recommends autoconf automake libtool openjdk-11-jre-headless
          apt-fast clean
          rm -rf install.sh /var/lib/apt/lists/* /usr/share/man
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build artifacts
        run: |
          docker build . -t builder
          echo ${{ secrets.ENC_KEY }} > encryptKeyWith
          docker run --rm -v ${PWD}:/project builder python3 build.py
      - name: Get version number
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') }}
        run: |
          apt-fast -y install --no-install-recommends libxml2-utils
          echo "::set-output name=version::$(xmllint --xpath 'app/version/text()' meta/hbl/meta.xml)"
        id: version
      - name: Upload Aroma version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Aroma
          path: out/Aroma/*
          if-no-files-found: warn
      - name: Upload Aroma debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Aroma-DEBUG
          path: out/Aroma-DEBUG/*
          if-no-files-found: error
      - name: Upload Channel version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Channel
          path: out/Channel/*
          if-no-files-found: warn
      - name: Upload Channel debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-Channel-DEBUG
          path: out/Channel-DEBUG/*
          if-no-files-found: error
      - name: Upload HBL version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-HBL
          path: out/HBL/*
          if-no-files-found: warn
      - name: Upload HBL debug version
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && (contains(github.event.head_commit.message, '-ALPHA') || contains(github.event.head_commit.message, '-BETA')) }}
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-${{ steps.version.outputs.version }}-HBL-DEBUG
          path: out/HBL-DEBUG/*
          if-no-files-found: error
      - name: Prepare release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          body: |
            Improvements to stability and usability:
            Further improvements to overall stability and other minor adjustments have been made to enhance the user experience.
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Aroma release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-Aroma.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-Aroma.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Aroma debug release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-Aroma-DEBUG.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-Aroma-DEBUG.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Channel release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-Channel.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-Channel.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Channel debug release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-Channel-DEBUG.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-Channel-DEBUG.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload HBL release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-HBL.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-HBL.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload HBL debug release
        if: ${{ startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.') && !endsWith(github.event.head_commit.message, '.') && !contains(github.event.head_commit.message, '-ALPHA') && !contains(github.event.head_commit.message, '-BETA') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: NUSspli-${{ steps.version.outputs.version }}-HBL-DEBUG.zip
          asset_path: zips/NUSspli-${{ steps.version.outputs.version }}-HBL-DEBUG.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
